version: '3.9'

services:
  backend:
    stop_signal: SIGINT
    build:
      dockerfile: api.Dockerfile
    working_dir: "/usr/src/app/api"
    ports:
      - "8000:8000"
    command: "uvicorn --factory newsletter.main:create_app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./src:/usr/src/app/api
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://localhost:8000/healthcheck/" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
networks:
  backend:
    driver: bridge